--  *********************
--  ELIMINACION DE TABLAS
--  *********************
DROP TABLE DETALLE_VENTA CASCADE CONSTRAINTS;
DROP TABLE VENTA CASCADE CONSTRAINTS;
DROP TABLE VENDEDOR CASCADE CONSTRAINTS;
DROP TABLE ADMINISTRATIVO CASCADE CONSTRAINTS;
DROP TABLE EMPLEADO CASCADE CONSTRAINTS;
DROP TABLE PRODUCTO CASCADE CONSTRAINTS;
DROP TABLE PROVEEDOR CASCADE CONSTRAINTS;
DROP TABLE COMUNA CASCADE CONSTRAINTS;
DROP TABLE REGION CASCADE CONSTRAINTS;
DROP TABLE MEDIO_PAGO CASCADE CONSTRAINTS;
DROP TABLE SALUD CASCADE CONSTRAINTS;
DROP TABLE AFP CASCADE CONSTRAINTS;
DROP TABLE MARCA CASCADE CONSTRAINTS;
DROP TABLE CATEGORIA CASCADE CONSTRAINTS;

--  *********************
--  CREACION DE TABLAS
--  *********************

CREATE TABLE CATEGORIA(
id_categoria NUMBER(3) NOT NULL,
nombre_categoria VARCHAR2(255) NOT NULL
);

ALTER TABLE CATEGORIA
ADD CONSTRAINT PK_categoria_id_categoria PRIMARY KEY (id_categoria); 

CREATE TABLE MARCA(
id_marca NUMBER(3) NOT NULL,
nombre_marca VARCHAR2(25) NOT NULL
);

ALTER TABLE MARCA
ADD CONSTRAINT pk_marca_id_marca PRIMARY KEY(id_marca);

CREATE TABLE AFP(
id_afp NUMBER(5) GENERATED BY DEFAULT AS IDENTITY (START WITH 210 INCREMENT BY 6) NOT NULL,
nom_afp VARCHAR2(255) NOT NULL
);

ALTER TABLE AFP
ADD CONSTRAINT pk_afp_id_afp PRIMARY KEY (id_afp);

CREATE TABLE SALUD(
id_salud NUMBER(4) NOT NULL,
nom_salud VARCHAR2(40) NOT NULL
);

ALTER TABLE SALUD
ADD CONSTRAINT pk_salud_id_salud PRIMARY KEY (id_salud);

CREATE TABLE MEDIO_PAGO(
id_mpago NUMBER(3) NOT NULL,
nombre_mpago VARCHAR2(50) NOT NULL
);

ALTER TABLE MEDIO_PAGO
ADD CONSTRAINT pk_medio_pago_id_mpago PRIMARY KEY (id_mpago);

CREATE TABLE REGION (
id_region NUMBER(4) NOT NULL,
nom_region VARCHAR2(255) NOT NULL
);

ALTER TABLE REGION
ADD CONSTRAINT pk_region_id_region PRIMARY KEY(id_region);

CREATE TABLE COMUNA(
id_comuna NUMBER(4) NOT NULL,
nom_comuna VARCHAR2(100) NOT NULL,
cod_region NUMBER(4) NOT NULL
);

ALTER TABLE COMUNA 
ADD CONSTRAINT pk_comuna_id_comuna PRIMARY KEY (id_comuna);

ALTER TABLE COMUNA 
ADD CONSTRAINT fk_comuna_cod_region FOREIGN KEY(cod_region) REFERENCES REGION(id_region); 

CREATE TABLE PROVEEDOR(
id_proveedor NUMBER(5) NOT NULL,
nombre_proveedor VARCHAR2(150) NOT NULL,
rut_proveedor VARCHAR2(10) NOT NULL,
telefono VARCHAR2(10) NOT NULL,
email VARCHAR2(200) NOT NULL,
direccion VARCHAR2(200) NOT NULL,
cod_comuna NUMBER(4) NOT NULL
);

ALTER TABLE PROVEEDOR
ADD CONSTRAINT pk_proveedor_id_proveedor PRIMARY KEY(id_proveedor);

ALTER TABLE PROVEEDOR 
ADD CONSTRAINT fk_proveedor_cod_comuna  FOREIGN KEY(cod_comuna) REFERENCES COMUNA(id_comuna);

CREATE TABLE PRODUCTO (
id_producto NUMBER(4) NOT NULL,
nombre_producto VARCHAR2(100) NOT NULL,
precio_unitario NUMBER NOT NULL,
origen_nacional CHAR(1) NOT NULL,
stock_minimo NUMBER(3) NOT NULL,
activo CHAR(1) NOT NULL,
cod_marca NUMBER(3) NOT NULL,
cod_categoria NUMBER(3) NOT NULL,
cod_proveedor NUMBER(5) NOT NULL
);

ALTER TABLE PRODUCTO
ADD CONSTRAINT pk_producto_id_producto PRIMARY KEY (id_producto);

ALTER TABLE PRODUCTO
ADD CONSTRAINT fk_producto_cod_marca FOREIGN KEY(cod_marca) REFERENCES MARCA (id_marca);

ALTER TABLE PRODUCTO
ADD CONSTRAINT fk_producto_cod_categoria FOREIGN KEY(cod_categoria) REFERENCES CATEGORIA (id_categoria);

ALTER TABLE PRODUCTO
ADD CONSTRAINT fk_producto_cod_proveedor FOREIGN KEY(cod_proveedor) REFERENCES PROVEEDOR (id_proveedor);

CREATE TABLE EMPLEADO(
id_empleado NUMBER(4) NOT NULL,
rut_empleado VARCHAR2(10) NOT NULL,
nombre_empleado VARCHAR2(25) NOT NULL,
apellido_paterno VARCHAR2(25) NOT NULL,
apellido_materno VARCHAR2(25) NOT NULL,
fecha_contratacion DATE NOT NULL,
sueldo_base NUMBER(10) NOT NULL,
bono_jefatura NUMBER(10),
activo CHAR(1) NOT NULL,
tipo_empleado VARCHAR2(25) NOT NULL,
cod_empleado NUMBER(4),
cod_salud NUMBER(4) NOT NULL,
cod_afp NUMBER(5) NOT NULL
);

ALTER TABLE EMPLEADO
ADD CONSTRAINT pk_empleado_id_empleado PRIMARY KEY (id_empleado);

ALTER TABLE EMPLEADO
ADD CONSTRAINT fk_empleado_cod_empleado FOREIGN KEY(cod_empleado) REFERENCES EMPLEADO (id_empleado);

ALTER TABLE EMPLEADO
ADD CONSTRAINT fk_empleado_cod_salud FOREIGN KEY(cod_salud) REFERENCES SALUD (id_salud);

ALTER TABLE EMPLEADO
ADD CONSTRAINT fk_empleado_cod_afp FOREIGN KEY(cod_afp) REFERENCES AFP (id_afp);

ALTER TABLE EMPLEADO
ADD CONSTRAINT ck_empleado_tipo_empleado CHECK (tipo_empleado IN ('Administrativo','Vendedor'));

CREATE TABLE ADMINISTRATIVO(
id_empleado NUMBER(4)
);

ALTER TABLE ADMINISTRATIVO
ADD CONSTRAINT pk_administrativo_id_empleado PRIMARY KEY (id_empleado);

ALTER TABLE ADMINISTRATIVO
ADD CONSTRAINT fk_administrativo_id_empleado FOREIGN KEY(id_empleado) REFERENCES EMPLEADO (id_empleado);

CREATE TABLE VENDEDOR(
id_empleado NUMBER(4),
comision_venta NUMBER(5,2)
);

ALTER TABLE VENDEDOR
ADD CONSTRAINT pk_vendedor_id_empleado PRIMARY KEY (id_empleado);

ALTER TABLE VENDEDOR
ADD CONSTRAINT fk_vendedor_id_empleado FOREIGN KEY(id_empleado) REFERENCES EMPLEADO (id_empleado);

CREATE TABLE VENTA(
id_venta NUMBER(4) GENERATED BY DEFAULT AS IDENTITY (START WITH 5050 INCREMENT BY 3) NOT NULL,
fecha_venta DATE NOT NULL,
total_venta NUMBER(10) NOT NULL,
cod_mpago NUMBER(3) NOT NULL,
cod_empleado NUMBER(4) NOT NULL
);

ALTER TABLE VENTA
ADD CONSTRAINT pk_venta_id_venta PRIMARY KEY (id_venta);

ALTER TABLE VENTA
ADD CONSTRAINT fk_venta_cod_mpago FOREIGN KEY(cod_mpago) REFERENCES MEDIO_PAGO (id_mpago);

ALTER TABLE VENTA
ADD CONSTRAINT fk_venta_cod_empleado FOREIGN KEY(cod_empleado) REFERENCES EMPLEADO (id_empleado);

CREATE TABLE DETALLE_VENTA(
cod_venta NUMBER(4) NOT NULL,
cod_producto NUMBER(4) NOT NULL,
cantidad NUMBER(6) NOT NULL
);

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT pk_detalle_venta PRIMARY KEY (cod_venta,cod_producto);

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT fk_detalle_venta_cod_venta FOREIGN KEY(cod_venta) REFERENCES VENTA (id_venta);

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT fk_detalle_venta_cod_producto FOREIGN KEY(cod_producto) REFERENCES PRODUCTO (id_producto);

--  *********************
--  MODIFICACIONES AL MODELO
--  *********************

ALTER TABLE EMPLEADO
ADD CONSTRAINT ck_empleado_sueldo_base CHECK (sueldo_base>=400000);

ALTER TABLE VENDEDOR 
ADD CONSTRAINT ck_vendedor_comision_venta CHECK(comision_venta BETWEEN 0 AND 0.25);

ALTER TABLE PRODUCTO
ADD CONSTRAINT ck_producto_stock_minimo CHECK(stock_minimo>=3);
 
ALTER TABLE PROVEEDOR
ADD CONSTRAINT uk_proveedor_email UNIQUE (email);

ALTER TABLE MARCA
ADD CONSTRAINT uk_marca_nombre_marca UNIQUE (nombre_marca);

ALTER TABLE DETALLE_VENTA
ADD CONSTRAINT ck_detalle_venta_cantidad CHECK (cantidad>=1);

--  *********************
--  POBLAMIENTO DEL MODELO
--  *********************

DROP SEQUENCE SE_SALUD_ID_SALUD;

CREATE SEQUENCE SE_SALUD_ID_SALUD
START WITH 2050
INCREMENT BY 10
NOCYCLE
CACHE 20;

DROP SEQUENCE SE_EMPLEADO_ID_EMPLEADO;

CREATE SEQUENCE SE_EMPLEADO_ID_EMPLEADO
START WITH 750
INCREMENT BY 3
NOCYCLE
CACHE 20;

INSERT INTO REGION (id_region,nom_region) VALUES(1,'Region Metropolitana'); 
INSERT INTO REGION (id_region,nom_region) VALUES(2,'Valparaiso'); 
INSERT INTO REGION (id_region,nom_region) VALUES(3,'Biobio'); 
INSERT INTO REGION (id_region,nom_region) VALUES(4,'Los Lagos'); 

INSERT INTO MEDIO_PAGO (id_mpago,nombre_mpago) VALUES(11,'Efectivo'); 
INSERT INTO MEDIO_PAGO (id_mpago,nombre_mpago) VALUES(12,'Tarjeta de debito'); 
INSERT INTO MEDIO_PAGO (id_mpago,nombre_mpago) VALUES(13,'Tarjeta de credito'); 
INSERT INTO MEDIO_PAGO (id_mpago,nombre_mpago) VALUES(14,'Cheque'); 

INSERT INTO AFP (nom_afp) VALUES('AFP Habitat');
INSERT INTO AFP (nom_afp) VALUES('AFP Cuprum');
INSERT INTO AFP (nom_afp) VALUES('AFP Provida');
INSERT INTO AFP (nom_afp) VALUES('AFP PlanVital');

INSERT INTO SALUD (id_salud,nom_salud) VALUES(SE_SALUD_ID_SALUD.NEXTVAL,'Fonasa');
INSERT INTO SALUD (id_salud,nom_salud) VALUES(SE_SALUD_ID_SALUD.NEXTVAL,'Isapre Colmena');
INSERT INTO SALUD (id_salud,nom_salud) VALUES(SE_SALUD_ID_SALUD.NEXTVAL,'Isapre Banmedica');
INSERT INTO SALUD (id_salud,nom_salud) VALUES(SE_SALUD_ID_SALUD.NEXTVAL,'Cruz Blanca');

INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'11111111-1','Marcela','Gonzalez','Perez',
DATE '2022-03-15',950000,80000,'S','Administrativo',null,2050,210);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'22222222-2','Jose','Muñoz','Ramirez',
DATE '2021-07-10',900000,75000,'S','Administrativo',null,2060,216);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'33333333-3','Veronica','Soto','Alarcon',
DATE '2020-01-05',880000,70000,'S','Vendedor',750,2060,228);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'44444444-4','Luis','Reyes','Fuentes',
DATE '2023-04-01',560000,null,'S','Vendedor',750,2070,228);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'55555555-5','Claudia','Fernandez','Lagos',
DATE '2023-04-15',600000,null,'S','Vendedor',753,2070,216);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'66666666-6','Carlos','Navarro','Vega',
DATE '2023-05-01',610000,null,'S','Administrativo',753,2060,210);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'77777777-7','Javiera','Pino','Rojas',
DATE '2023-05-10',650000,null,'S','Administrativo',750,2050,210);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'88888888-8','Diego','Mella','Contreras',
DATE '2023-05-12',620000,null,'S','Vendedor',750,2060,216);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'99999999-9','fernanda','Salas','Herrera',
DATE '2023-05-18',570000,null,'S','Vendedor',753,2070,228);
INSERT INTO EMPLEADO (id_empleado,rut_empleado,nombre_empleado,apellido_paterno,apellido_materno,fecha_contratacion,sueldo_base,bono_jefatura,
activo,tipo_empleado,cod_empleado,cod_salud,cod_afp) VALUES(SE_EMPLEADO_ID_EMPLEADO.NEXTVAL,'10101010-0','Tomas','Vidal','Espinoza',
DATE '2023-06-01',530000,null,'S','Vendedor',null,2050,222);

INSERT INTO VENTA (fecha_venta,total_venta,cod_mpago,cod_empleado) VALUES(DATE '2023-05-12',225990,12,771);
INSERT INTO VENTA (fecha_venta,total_venta,cod_mpago,cod_empleado) VALUES(DATE '2023-10-23',524990,13,777);
INSERT INTO VENTA (fecha_venta,total_venta,cod_mpago,cod_empleado) VALUES(DATE '2023-02-17',466990,11,759);

-- *********************
--  INFORME 1
-- *********************

SELECT id_empleado AS IDENTIFICADOR,nombre_empleado ||' '|| apellido_paterno ||' '|| apellido_materno AS NOMBRE_COMPLETO,sueldo_base AS SALARIO,
bono_jefatura AS BONIFICACION,
(bono_jefatura+sueldo_base) AS SALARIO_SIMULADO
FROM EMPLEADO
WHERE activo='S' AND bono_jefatura IS NOT NULL
ORDER BY SALARIO_SIMULADO DESC,apellido_paterno DESC;

-- *********************
--  INFORME 2
-- *********************

SELECT nombre_empleado ||' '|| apellido_paterno ||' '|| apellido_materno AS EMPLEADO,sueldo_base AS SUELDO,
sueldo_base*0.08 AS POSIBLE_AUMENTO,
(sueldo_base*0.08+sueldo_base) AS SALARIO_SIMULADO
FROM EMPLEADO
WHERE sueldo_base BETWEEN 550000 AND 800000
ORDER BY SUELDO_BASE ASC;


